name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - name: grant access
        run: sudo chmod +x mvnw
      
      - name: Start project
        run: nohup ./mvnw spring-boot:run &
        
      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
            time: '30s'
    
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "${{ github.workspace }}/postman/collections/spring-postman-newman-cicd.json" --integration-id "139227-${{ github.run_id }}"
